import { Conversation, ConversationNode, EdgeKind, Message } from './types'
import { NODE_WIDTH, NODE_HEIGHT, MAIN_GAP_Y, BRANCH_GAP_X } from './constants'

const GAP_X = NODE_WIDTH + BRANCH_GAP_X
const GAP_Y = NODE_HEIGHT + MAIN_GAP_Y

const OX = 100
const OY = 100

// Fixed base timestamp so the seed is deterministic.
const T0 = Date.UTC(2026, 0, 1)
let seq = 0

function exchange(nodeId: string, question: string, answer: string): Message[] {
  return [
    { id: `${nodeId}-u`, role: 'user', content: question, createdAt: T0 + seq++ },
    { id: `${nodeId}-a`, role: 'assistant', content: answer, model: 'claude-opus-4-8', createdAt: T0 + seq++ },
  ]
}

function node(
  id: string,
  parentId: string | null,
  edgeKind: EdgeKind,
  x: number,
  y: number,
  question: string,
  answer: string
): ConversationNode {
  return { id, parentId, edgeKind, position: { x, y }, messages: exchange(id, question, answer) }
}

const NODES: ConversationNode[] = [
  node(
    'root', null, 'continue', OX, OY,
    'What is the relationship between emergence and consciousness?',
    `Emergence describes how complex properties arise from simpler constituents — a flock's murmurations from individual birds, wetness from water molecules. Consciousness appears to exhibit a similar quality: subjective experience arising from neural substrate. The hard problem, though, is that emergence typically describes third-person observable properties, while consciousness is irreducibly first-person. This gap — between functional emergence and phenomenal experience — is what Chalmers calls the "explanatory gap."`
  ),
  node(
    'n1', 'root', 'continue', OX, OY + GAP_Y,
    'Can we close that gap with a better theory of information?',
    `Integrated Information Theory (IIT) attempts exactly this. Tononi's φ (phi) quantifies the integrated information generated by a system above its parts. High-φ systems are, by definition, conscious to some degree — and the theory predicts information integration is both necessary and sufficient. The appeal: substrate-neutral and mathematically precise. The criticism: computationally intractable and assigns consciousness to entities that seem implausible — simple grids, logic circuits.`
  ),
  node(
    'ba', 'root', 'branch', OX + GAP_X, OY,
    'How does novelty emergence compare in evolutionary biology?',
    `In evolution, novelty emerges through variation-selection-retention cycles operating on genetic information. The key mechanism isn't complexity per se, but evolvability — the capacity to generate heritable variation. Kauffman's NK fitness landscapes show modularity and near-decomposability are prerequisites for open-ended evolution. Biological emergence has a structural condition: decomposable enough to vary locally, yet integrated enough to transmit innovations.`
  ),
  node(
    'bb', 'n1', 'branch', OX + GAP_X, OY + GAP_Y,
    'Does IIT make different predictions from Global Workspace Theory?',
    `Yes, substantially. GWT (Baars, Dehaene) locates consciousness in a global broadcast — local processors compete and one wins access to a "workspace" that signals brain-wide. IIT disagrees: the cerebellum has billions of neurons but contributes little to consciousness because it's modular and low-φ. GWT predicts the cerebellum should contribute if its contents win the broadcast. Evidence from cerebellar lesion patients weakly favors IIT on this point.`
  ),
  node(
    'ba1', 'ba', 'branch', OX + GAP_X * 2, OY,
    'Is modularity at odds with consciousness? It helps evolution but suppresses IIT.',
    `This is a genuine tension. Modularity enables evolution (local variation without global disruption) but suppresses consciousness (low φ due to decomposability). The resolution may be hierarchical: modules interact at higher levels of integration that achieve high φ. Marr's levels of analysis suggest these aren't competing — a system can be modular at the implementational level while highly integrated at the algorithmic level. The brain's cortical hierarchy does exactly this.`
  ),
]

// NOTE: No longer the default state — the app starts with a blank canvas and
// persists to localStorage. Kept as demo content for a future "Load demo" action.
export const INITIAL_CONVERSATION: Conversation = {
  id: 'conv-seed',
  title: 'Emergence & Consciousness',
  rootId: 'root',
  nodes: NODES,
  createdAt: T0,
  updatedAt: T0,
}
