import { NodeData } from './types'
import { NODE_WIDTH, NODE_HEIGHT, MAIN_GAP_Y, BRANCH_GAP_X } from './constants'

const GAP_X = NODE_WIDTH + BRANCH_GAP_X
const GAP_Y = NODE_HEIGHT + MAIN_GAP_Y

const OX = 100
const OY = 100

export const INITIAL_NODES: NodeData[] = [
  {
    id: 'root',
    parentId: null,
    question: 'What is the relationship between emergence and consciousness?',
    answer: `Emergence describes how complex properties arise from simpler constituents — a flock's murmurations from individual birds, wetness from water molecules. Consciousness appears to exhibit a similar quality: subjective experience arising from neural substrate. The hard problem, though, is that emergence typically describes third-person observable properties, while consciousness is irreducibly first-person. This gap — between functional emergence and phenomenal experience — is what Chalmers calls the "explanatory gap."`,
    x: OX,
    y: OY,
    isMainThread: true,
    branchDepth: 0,
  },
  {
    id: 'n1',
    parentId: 'root',
    question: 'Can we close that gap with a better theory of information?',
    answer: `Integrated Information Theory (IIT) attempts exactly this. Tononi's φ (phi) quantifies the integrated information generated by a system above its parts. High-φ systems are, by definition, conscious to some degree — and the theory predicts information integration is both necessary and sufficient. The appeal: substrate-neutral and mathematically precise. The criticism: computationally intractable and assigns consciousness to entities that seem implausible — simple grids, logic circuits.`,
    x: OX,
    y: OY + GAP_Y,
    isMainThread: true,
    branchDepth: 0,
  },
  {
    id: 'ba',
    parentId: 'root',
    question: 'How does novelty emergence compare in evolutionary biology?',
    answer: `In evolution, novelty emerges through variation-selection-retention cycles operating on genetic information. The key mechanism isn't complexity per se, but evolvability — the capacity to generate heritable variation. Kauffman's NK fitness landscapes show modularity and near-decomposability are prerequisites for open-ended evolution. Biological emergence has a structural condition: decomposable enough to vary locally, yet integrated enough to transmit innovations.`,
    x: OX + GAP_X,
    y: OY,
    isMainThread: false,
    branchDepth: 1,
  },
  {
    id: 'bb',
    parentId: 'n1',
    question: 'Does IIT make different predictions from Global Workspace Theory?',
    answer: `Yes, substantially. GWT (Baars, Dehaene) locates consciousness in a global broadcast — local processors compete and one wins access to a "workspace" that signals brain-wide. IIT disagrees: the cerebellum has billions of neurons but contributes little to consciousness because it's modular and low-φ. GWT predicts the cerebellum should contribute if its contents win the broadcast. Evidence from cerebellar lesion patients weakly favors IIT on this point.`,
    x: OX + GAP_X,
    y: OY + GAP_Y,
    isMainThread: false,
    branchDepth: 1,
  },
  {
    id: 'ba1',
    parentId: 'ba',
    question: 'Is modularity at odds with consciousness? It helps evolution but suppresses IIT.',
    answer: `This is a genuine tension. Modularity enables evolution (local variation without global disruption) but suppresses consciousness (low φ due to decomposability). The resolution may be hierarchical: modules interact at higher levels of integration that achieve high φ. Marr's levels of analysis suggest these aren't competing — a system can be modular at the implementational level while highly integrated at the algorithmic level. The brain's cortical hierarchy does exactly this.`,
    x: OX + GAP_X * 2,
    y: OY,
    isMainThread: false,
    branchDepth: 2,
  },
]
